-- phpMyAdmin SQL Dump
-- version 4.8.3
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Waktu pembuatan: 29 Apr 2019 pada 17.34
-- Versi server: 10.1.36-MariaDB
-- Versi PHP: 7.2.11

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `qas_asma`
--

-- --------------------------------------------------------

--
-- Struktur dari tabel `data`
--

CREATE TABLE `data` (
  `id_data` int(11) NOT NULL,
  `pertanyaan` text NOT NULL,
  `jawaban` mediumtext NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data untuk tabel `data`
--

INSERT INTO `data` (`id_data`, `pertanyaan`, `jawaban`) VALUES
(1, 'asma ambroxol teosal', 'Teosal mengandung zat aktif teofilin dan salbutamol. Keduanya merupakan jenis obat bronkodilator, yaitu bekerja untuk melebarkan saluran napas dengan cara melemaskan otot pernapasan sehingga diharapkan keluhan sesak berkurang. Sedangkan ambroxol merupakan jenis mukolitik, yaitu berfungsi untuk mengencerkan lendir di saluran napas sehingga lebih mudah dikeluarkan melalui mekanisme batuk. Keduanya memiliki cara kerja yang berbeda dan seringkali dikombinasikan pada beberapa kondisi misalnya pada kasus asma. Anda dapat mengonsumsi keduanya dalam waktu yang bersamaan jika memang sebelumnya telah diresepkan, namun sebaiknya dalam jangka waktu tertentu yang telah direkomendasikan oleh dokter yang menangani sesuai dengan kondisi medis anda agar tidak terjadi efek samping yang tidak diinginkan. Jika sudah diresepkan beberapa jenis obat, sebaiknya baca kembali petunjuk pemakaiannya di label obat. Beberapa jenis obat memang tidak untuk dikonsumsi sampai habis, yakni hanya jika ada gejala saja, sementara yang lainnya perlu dikonsumsi hingga jangka waktu tertentu.   '),
(2, 'asma hipertensi', 'Hipertensi merupakan suatu kondisi dimana tekanan darah lebih tinggi dari normal. Hipertensi terjadi ketika tekanan darah sistolik melebihi 130 mmHg atau tekanan darah diastolik melebihi 90 mmHg pada saat dilakukan pengukuran pada kondisi individu tenang, tidak setelah aktifitas fisik yang memacu kerja jantung.\r\n\r\nHipertensi dapat dibagi menjadi hipertensi primer, dimana hipertensi terjadi tanpa sebab yang jelas atau hipertensi sekunder, dimana hipertensi terjadi dengan adanya penyakit yang mendasari / menyebabkan peningkatan tekanan darah seperti gangguan ginjal, kelainan kelenjar tiroid, kondisi kehamilan, gangguan pembuluh darah, hiperkolesterolemia, efek samping obat-obatan.\r\n\r\nPada pengobatan hipertensi dapat menggunakan obat melalui konsumsi oral (obat minum) ataupun obat secara intravena (melalui infus, dapat digunakan pada kondisi hipertensi emergensi, pasien tidak sadarkan diri, atau dalam perawatan di Rumah Sakit). Ada berbagai jenis golongan anti hipertensi yang dapat dipilih sebagai modalitas pengobatan seperti ACE inhibitor, Calcium Channel Blockers, Diuretics, Angiotensin Receptor Blockers, Beta-blockers. Pada kondisi hipertensi yang dialami dengan penyakit komorbid asma, disarankan untuk menggunakan pengobatan anti hipertensi golongan Calcium Channel Blockers karena memiliki efek menurunkan tekanan darah dan juga efek bronkodilator. Tentunya bila ada kerabat / diri anda memiliki kondisi ini disarankan untuk konsultasi pada dokter atau dokter spesialis penyakit dalam untuk kontrol berkala, dilakukan pemeriksaan dan penatalaksanaan yang tepat untuk kondisi ini.\r\n\r\nPerlu diingat bahwa panel Alodokter digunakan untuk membantu dan memberikan informasi kesehatan bagi masyarakat yang memerlukan. Untuk keperluan pendidikan, tentunya mencari ilmu dari sumber ilmiah dan buku teks sebagai dasar teori dan ilmu harus dilakukan oleh anda sendiri. Untuk informasi lebih lanjut mengenai hipertensi dapat mengakses tautan ini.\r\n'),
(3, 'asma bronkial sesak nafas alergi', 'Asma yang sudah berjalan selama beberapa bulan dan setiap hari atau hampir setiap hari kambuh kemungkinan dapat digolongkan masuk kepada asma episodik sering atau asma persisten. Tentunya hal ini memerlukan penanganan lebih lanjut. Penanganan dapat berupa pemeriksaan fungsi paru, tes alergi, atau perubahan regimen obat.\r\n\r\nIbu sebaiknya bicarakan hal ini dengan dokter anak yang merawat, komunikasikan apakah perlu anak mendapatkan tindakan lanjutan, opsi apa saja yang ada. Jangan membawa anak kepada dokter spesialis penyakit dalam karena anak memiliki kebutuhan penanganan penyakit yang berbeda dengan dewasa. Pilihan alternatifnya adalah bawa anak anda kepada dokter spesialis paru. Tanyakan pada dokter anak anda apakah perlu anda dirujuk kepada ahli paru. Bicarakan pula mengenai kemungkinan tes alergi. Perhatikan apakah mungkin terdapat benda yang memicu alergi pada anak, misalnya tumpukan barang berdebu, polusi, asap rokok, debu pembangunan, bulu hewan, atau makanan dan minuman. Perbaiki ventilasi kamar dan rumah. '),
(4, 'asma badan berasa lemes mual pegel acetylstenie', 'Asma dapat kambuh akibat terjadi pajanan terhadap pencetusnya dimana kondisi serangan ini dapat timbul ringan sampai berat. Jika kekambuhan cukup sering maka perlu untuk dilakukan evaluasi baik pengobatan yang diberikan maupun faktor apa yang memicunya agar dapat dihindari dan asma tidak kembali kambuh.\r\n\r\nObat yang digunakan untuk mengelola asma sendiri ada beberapa macam, baik obat yang untuk meredakan ketika serangan sedang timbul maupun obat yang digunakan untuk mengelola agar tidak kembali terjadi serangan. Obat yang diberikan sendiri juga biasanya digunakan untuk mengatasi gejala lain atau gejala yang menjadi pemicu seperti misalnya ketika sedang batuk dan pilek.\r\n\r\nObat yang diberikan untuk Anda adalah acetylcysteine yang merupakan obat antimukolitik yang berfungsi untuk mengencerkan dahak yang mengganggu saluran pernapasan, obat ini memiliki efek samping seperti mual, muntah, sariawan, mengantuk, pilek ataupun demam. Sedangkan obat kedua yaitu obat yang berisi antihistamin dan kotrikosteroid yang berfungsi untuk mengatasi alergi dan juga peradangan dimana pada asma dapat terjadi peradangan dan penyempitan pada saluran pernapasan. Jika timbul gejala seperti yang dirasakan kondisi tersebut dapat mungkin terjadi akibat efek samping obat ataupun kondisi lain yang menjadi penyebabnya seperti misalnya jika terjadi gangguan pencernaan ataupun demam dan infeksi saluran pernapasan.\r\n\r\nUntuk itu perlu diperhatikan jika mengonsumsi obat serupa dan kembali mengalami hal yang sama maka perlu untuk dihindari karena dapat mungkin merupakan efek samping obat. Periksakan kembali kondisi Anda dan terangkan pada dokter mengenai kondisi yang dialami dan obat apa yang dikonsumsi sehingga dapat dipertimbangkan untuk mengganti dengan obat lain yang sesuai dengan kondisi Anda. Jika timbul reaksi alergi yang lebih berat, sesak napas kembali menyerang, dan timbul keluhan lain seperti ruam kulit, bibir, kelopak mata terasa kebas atau membengkak maka segera datang ke fasilitas kesehatan untuk mendapatkan penanganan.  '),
(5, 'nafas terengah dada sakit jari kaki tangan sulit gerak mata', 'Asma adalah reaksi alergi yang terjadi pada saluran napas. Ditandai dengan sesak napas disertai suara \"ngi\". Terjadi akibat alergen (seperti debu, serbuk bunga, makanan bahan udang dan telur, udara dingin dan lain-lain) menyebabkan saluran napas mengalami konstriksi sehingga menyempit, ditambah lapisan mukosa saluran napas menghasilkan lendir dalam jumlah banyak sehingga menutupi saluran napas yang menyempit. Maka muncullah sesak napas. Pada saat menghembuskan napas, udara keluar diantara saluran napas yang menyempit dan ditutupi lendir, sehingga muncul suara \"ngik\". Hal ini hanya terjadi pada seseorang yang hipersensitif. Terdapat kaitan yang erat dengan faktor keturunan.\r\nSeseorang yang mengalami asma, dapat memiliki reaksi alergi dalam bentuk yang lain, dari yang ringan (seperti bintik kemerahan yang gatal pada kulit akibat berkontak dengan logam jam tangan penyebab reaksi alergi, bersin-bersin pagi hari akibat debu) hingga kondisi yang berat (reaksi anafilaksis dan angioudema) yang ditandai peningkatan denyut nadi, penurunan kesadaran, muka bengkak dan bibir bengkak). Untuk itu, sebaiknya hindarilah kondisi yang dapat memicu reaksi, seperti udara dingin malam hari. Apabila harus mengikuti kegiatan camping, siapkanlah pakaian penghangat lengkap dari kaus kaki hingga topi dan obat-obatan anti alergi. Karena pada penyakit asma pun dapat terjadi serangan asma yang berat, disebut Serangan asmatikus. Dimana dapat hingga menyebabkan penurunan kesadaran dan henti napas sehingga membutuhkan perawatan intensif.\r\nUntuk apa yang telah anda alami. Sebaiknya berkonsultasi dengan dokter paru anda. Agar dokter dapat melakukan pemeriksaan pada paru-paru anda. Agar dokter dapat menilai derajat berat ringannya penyakit asma pada anda. Dan dapat memberikan pengobatan yang sesuai berdasarkan kondisi berat ringannya penyakit anda.         '),
(6, 'sesak batuk asma', 'Batuk adalah salah satu cara tubuh dalam mencegah atau mengeluarkan “benda asing” atau zat/partikel tertentu ke saluran pernafasan. Batuk yang hanya sekali-sekali masih bisa disebut wajar, namun jika sudah berulang kali, berhari-hari, hingga berdahak, berdarah, sesak nafas, demam, maka batuk tersebut merupakan salah satu tanda dari adanya penyakit tertentu.Batuk dapat disebabkan oleh infeksi (misalnya: infeksi saluran pernafasan atas, pneumonia, TB, dl), asma, bronchitis, konsumsi obat darah tinggi tertentu, dll.\r\n\r\nAsma sendiri merupakan penyakit kronis (jangka panjang) dimana terjadi penyempitan bronchus (saluran/pipa2 pernafasan di paru-paru) karena seseorang tersebut memiliki sistem saluran pernafasan yang lebih “sensitive” terhadap sesuatu. Gejala asma misalnya sesak nafas, nafas berbunyi mengi saat mengeluarkan nafas, dan batuk-batuk. Gejala tersebut muncul secara hilang-timbul, misalnya ketika terpapar hal yang membuat alergi, stress, zat-zat yang membuat iritasi saluran nafas, maka gejala-gejala tersebut dapat muncul. Memiliki keluarga yang memiliki riwayat asma dapat meningkatkan kemungkinan seseorang untuk menderita asma juga.\r\n\r\nBatuk-batuk merupakan salah 1 gejala asma, namun bisa juga karena kondisi penyakit lain seperti yang sudah saya sebutkan di atas. Untuk menentukan penyebabnya, sebaiknya Anda pergi ke dokter untuk dilakukan pemeriksaan fisik dan penunjang yang diperlukan, misalnya tes darah lengkap, foto ronsen, spirometry, dll. Pengobatannya tergantung dari penyebabnya.\r\n\r\nBersin-bersin bisa disebabkan karena rhinitis (radang pada hidung), bisa karena alergi, infeksi, gangguan hormonal, stress, atau vasomotor. Telinga yang terasa penuh bisa disebabkan karena adanya gangguan pada fungsi tuba eustachius (saluran yang menghubungkan antara tenggorokan dengan telinga) karena ada rhinitis, tonsilitis, radang di telinga, dll; atau karena ada penyumbatan di telinga, misalnya karena penumpukan cerumen (kotoran telinga) atau peradangan di telinga luar atau telinga tengah. Untuk menentukan penyebabnya, harus dilakukan pemeriksaan langsung oleh dokter atau dokter spesialis THT.\r\n\r\nJangan tunda untuk ke dokter jika batuk tidak kunjung reda lebih dari 7 hari, batuk terus berulang, batuk disertai dahak, demam, sesak nafas, batuk disertai darah. Jika memiliki alergi, hindari paparan terhadap hal-hal yang dapat mencetuskan alergi tersebut.  '),
(7, 'ventolin inhaler asma sesak hidung tersumbat bibir kebas kelopak mata bengkak alergi ctm', 'Obat yang anda sebutkan mengandung salbutamol. Obat ini bekerja mengatasi penyumbatan saluran napas dengan melebarkan otot-otot saluran napas. Sehingga sering digunakan untuk mengatasi sesak nafas akibat asma dan PPOK (penyakit paru obstruksi kronis).\r\nSebelum anda menggunakan obat ini, harap membaca terlebih dahulu tanggal kadaluarsa obat dan kertas petunjuk obat (cara menggunakan obat dan cara penyimpanan obat).\r\nSetiap obat memiliki efek samping. Salah satu efek samping dari obat ini adalah reaksi alergi yang dapat muncul pada seseorang yang hipersensitif.\r\nAdapun yang terjadi pada anda, dapat merupakan bagian dari alergi anda yang muncul berat atau dapat disebabkan reaksi alergi terhadap obat salbutamol yang anda gunakan. Perlu untuk anda ketahui, reaksi alergi dapat muncul pada usia berapa saja dan dapat muncul pada hal-hal yang sebelumnya justru tidak menimbulkan reaksi alergi. Reaksi alergi yang baru muncul pada masa dewasa diduga akibat beberapa hal berikut, yaitu :\r\n1. Terdapat reaksi alergi pada masa anak-anak, namun lupa.\r\n2. Debu dan polutan mempengaruhi daya tahan tubuh.\r\n3. Perbedaan lingkungan saat reaksi muncul dengan lingkungan sebelumnya, di mana lingkungan sebelumnya higienis sehingga tidak terpapar kuman penyebab penyakit, sehingga sistem imun tidak berkembang.\r\nReaksi alergi memang tidak dapat diobati secara total. Namun dapat dilakukan pencegahan agar tidak terjangkit dengan menghindari pemicunya. Untuk itu, perlu bagi anda mengetahui hal yang menjadi penyebab munculnya reaksi alergi. Anda juga harus kembali kontrol dengan dokter anda. Agar dokter dapat menilai perkembangan pengobatan anda sebelumnya. Dokter juga akan memberikan anda obat yang diperlukan, seperti obat antiperadangan golongan kortikosteroid.    '),
(8, 'lodomer', 'Lodomer merupakan suatu merk dagang dengan kandungan haloperidol didalamnya, haloperidol sendiri bukanlah obat asma, namun suatu obat yang diindikasikan untuk kondisi medis seperti masalah kesehatan mental dan psikologis ataupun gangguan sistem saraf pusat yang memicu timbulnya gerakan-gerakan tidak wajar dan tidak bisa dikendalikan.\r\n\r\nMaka itu harus dikaji secara lebih seksama, kondisi medis apakah yang sebenarnya Anda alami sehingga perlu mengknsumsi obat tersebut? baik itu kondisi kesehatan mental ataupun sistem saraf pusat. Disisi lain beberapa efek samping haloperidol yang mungkin timbul adalah mulut terasa kering, sakit kepala, sulit buang air kecil, gemetaran, berdebar-debar, berkeringat, otot terasa kaku, dan merasa linglung.\r\n\r\nSedangkan asma adalah suatu kondisi dimana saluran pernafasan mengalami penyempitan sehingga timbulah rasa sulit bernafas atau sesak, pemicu asma setiap individu bisa berbeda-beda, seperti misalnya asap rokok, debu, aktivitas fisik, kelembapan udara dan suhu, atau terapapr suatu zat kimia tertentu. Penanganan asma ditangani dengan obat-obatan pelega serangan asma dan obat untuk mencegah kekambuhan asma. Asma merupakan penyakit jangka panjang yang bisa dikontrol dengan cara menghindari pemicunya dan mengkonsumsi obat untuk mencegah terjadinya serangan asma atau bahkan tubuh mulai toleran/terbiasa sehingga seolah serangan asma tidak muncul kembali sehingga dianggap sembuh, namun tetap saja ada kemungkinan suatu hari nanti serangan asma bisa muncul kembali.\r\n\r\nSaran untuk Anda adalah memeriksakan diri kembali ke dokter secara langsung untuk mengkaji kondisi kesehatan Anda atas penggunaan haloperidol tersebut, sebab obat tersebut termasuk golongan obat keras yang apabila penggunaanya tidak tepat sesuai indikasi ataupun melakukan penyalahgunaan obat dapat menyebabkan berbagai efek yang tidak baik bagi kesehatan.  '),
(9, 'asma hidung alergi', 'Pada dasarnya, asma adalah kondisi ketika tubuh berespon berlebihan terhadap suatu stimulus tertentu dengan menyempitkan saluran napas, sehingga penderitanya merasa tidak puas dalam bernapas dan merasa oksigen yang dihirupnya tidak cukup. Inilah yang memicu pernapasan cepat ketika asma itu kumat.\r\n\r\nPenyebab pasti mengapa asma timbul masih belum diketahui. Namun beberapa kondisi yang bisa memicu timbulnya asma adalah:\r\n\r\n•	Debu, polusi asap\r\n•	Aktivitas fisik\r\n•	Stress, emosi berlebihan\r\n•	Bulu hewan, serbuk bunga\r\n•	Alergi terhadap bahan tertentu\r\n•	Udara dingin\r\n•	Infeksi paru-paru atau saluran napas\r\n•	Kondisi interior ruangan yang lembap, dan berjamur\r\n•	Makanan atau minuman tertentu\r\n•	Obat-obatan tertentu\r\nSehingga pada kasus pimpinan Anda, kemungkinan kondisinya terjadi bukan karena hidungnya lega, karena inti dari penyakit ini adalah penyempitan saluran napas, tidak mungkin justru tidak kambuh dengan menyempitkan saluran napas dengan menyumbat hidung. Yang mungkin terjadi adalah asmanya kambuh ketika ada debu, asap atau lain sebagainya disekitarnya, dan dengan menyumbat hidungnya, debu-debu tersebut tersaring. Untuk menyikapi ini sebenarnya pimpinan Anda cukup menggunakan masker.\r\n\r\nNamun begitu, tetap diperlukan pemeriksaan langsung karena tanpa melihatnya secara langsung, bisa jadi ada kesalahpahaman. Maka dari itu, saran kami sebaiknya pimpinan Anda tetap memeriksakan dirinya ke dokter untuk mendapatkan pemeriksaan lebih lanjut.   '),
(10, 'asma bayi', 'Asma merupakan penyakit peradangan kronik yang terjadi pada saluran pernafasan sehingga saluran pernafasan menjadi menyempit dan menyebabkan sulit bernafas. Asma ini dapat menyerang anak-anak maupun dewasa. Asma ini biasanya muncul pada orang-orang dengan riwayat keluarga yang menderita asma, memiliki riwayat keluarga dengan penyakit alergi/atopik, atau sedang mengalami infeksi saluran pernafasan. Gejala yang muncul biasanya sesak disertai bunyi mengi, batuk, pilek, demam, dan lain-lain.\r\n\r\nAsma pada anak usia kurang dari 2 tahun umumnya sulit ditegakkan karena biasanya keluhannya mirip dengan penyakit infeksi saluran pernafasan lainnya, salah satu yang tersering pada anak kurang dari 2 tahun adalah bronkiolitis. Oleh karena itu untuk memastikan penyebabnya adalah asma atau bukan sebaiknya konsultasikan ke dokter anak, dokter akan melakukan tanya jawab mengenai keluhan yang timbul dan riwayat kesehatan dalam keluarga, pemeriksaan fisik, dan beberapa pemeriksaan penunjang bila dibutuhkan. Dokter akan memberikan penanganan sesuai dengan penyebab yang mendasari. Bila keluhan disebabkan asma, maka dokter akan memberikan pengobatan sesuai dengan pedoman penanganan asma pada anak. Dokter mungkin akan memberikan obat-obatan minum atau melakukan nebulisasi/pengasapan dengan obat yang mengandung pelega pernafasan bila dibutuhkan. Karena asma ini adalah penyakit yang diturunkan dan dicetuskan oleh sesuatu, maka sebaiknya cari tahu terlebih dahulu faktor yang dapat mencetuskan asma pada anak anda sehingga dapat dihindari dan serangan asma bisa tidak terjadi. '),
(11, 'tidur nafas demam', 'Sistem pernapasan pada manusia terdiri dari banyak organ mulai dari organ pernapasan serta persarafan yang mengatur pola napas dimana tubuh akan mengirimkan sinyal pada otak untuk menggerakkan sistem pernapasan. Sistem pernapasan sendiri diatur oleh pusat pernapasan yang bertanggung jawab untuk mengontrol pernapasan secara otomatis sehingga kita tidak akan lupa bernapas baik saat beraktivitas ataupun saat tidur. Baik secara sadar atau tidak tetapi kita juga dapat mengatur untuk mengendalikan napas terlebih pada kondisi tertentu seperti misalnya saat berenang, saat berlari dan lainnya.\r\n\r\nJika terdapat gangguan pada saluran pernapasan hal ini yang dapat membuat timbulnya gangguan seperti saluran napas yang tersumbat, hidung mampet, pilek, batuk dan lainnya sehingga merasakan adanya gangguan pada jalan napas. Dalam hal ini banyak yang menjadi penyebabnya mulai dari infeksi saluran napas, flu, batuk pilek ataupun terjadi sesak napas karena kondisi lain seperti misalnya gangguan pada fungsi paru atau penyakit menahun seperti asma.\r\n\r\nUntuk membantu agar dapat lebih nyaman saat tidur dan mengatasi hidung tersumbat dapat dilakukan beberapa upaya diantaranya dengan membuat suhu ruangan tidak terlalu dingin, banyak mengonsumsi cairan terlebih air hangat, mandi air hangat, menghirup uap air hangat, menggunakan bantal yang lebih tinggi saat tidur, menggunakan obat pelega saluran napas baik obat minum, obat hirup ataupun obat tetes jika diperlukan dan periksakan diri pada dokter jika keluhan demam berlanjut ataupun timbul disertai gejala lain seperti sesak napas, bibir kuku tampak kebiruan, demam tinggi, mual dan muntah serta sakit kepala hebat.   '),
(12, 'asma batuk teosal dexamethasone ambroxol nyeri tremor pegal lengan telapak tangan', 'Tidak hanya sesak napas dan napas berbunyi (mengi), asma juga bisa menyebabkan Anda batuk-batuk. Serangan asma ini kerap dicetuskan oleh beragam faktor, termasuk pajanan alergen, substansi udara tertentu, infeksi virus atau bakteri, tekanan mental berat, refuks asam lambung, konsumsi obat tertentu, dan sebagainya. Hidung berair yang Anda alami mungkin saja merupakan bagian dari salah satu pencetus asma di atas, misalnya alergi, infeksi, dan sebagainya.\r\n\r\nUntuk mencegah kekambuhan sekaligus meredakan serangan, penderita asma tidak jarang memang perlu menjalani pengobatan dalam waktu yang lama, termasuk juga obat-obatan sebagaimana yang Anda konsumsi. Selama obat ini Anda konsumsi sesuai anjuran dokter, seringnya kondisi ini tidaklah berbahaya. Namun memang, sebagaimana obat dan tindakan medis lainnya, obat ini tidak luput dari efek samping. Kondisi Anda yang mengalami tremor halus dan juga pegal-pegal bisa merupakan salah satu manifestasi efek samping konsumsi obat ini (khususnya teofilin dan salbutamol). Bisa juga, selain akibat efek samping obat, tremor muncul akibat sebab lain, misalnya gangguan kecemasan, hipoglikemia, berlebihan mengkonsumsi kafein, hipertiroidisme, kelelahan, kebiasaan merokok, sindroma putus obat atau alkohol, parkinson, gangguan otak, dan sebagainya. Sedangkan, pegal, bisa juga terjadi akibat kelelahan, fluktuasi hormonal, infeksi virus atau bakteri, fibromyalgia, syaraf kejepit, gangguan mental, dan sebagainya.\r\n\r\nJika keluhan hanya terjadi sementara, seringnya kondisi ini tidaklah berbahaya. Namun, jika keluhan yang Anda alami cukup mengganggu Anda, sebaiknya Anda tidak tinggal diam. Periksakan langsung diri Anda ke dokter atau dokter spesialis syaraf supaya diberikan penanganan yang terbaik.\r\n\r\nSementara ini, Anda bisa lakukan dulu upaya berikut:\r\n\r\n•	Hanya konsumsi obat sesuai saran dokter, jangan menambahkan, mengurangi, atau mengubah dosis sesuka hati\r\n•	Tidak merokok, jauhi alkohol, dan narkoba\r\n•	Kompres lengan dan tangan yang pegal dengan air hangat\r\n•	Rajin berolahraga\r\n•	Hindari pencetus asma Anda\r\n•	Kelola stres dan emosi Anda dengan baik\r\n•	Tidur dan bangun lebih teratur\r\n•	Makan makanan sehat dan bergizi  '),
(13, 'sesak batuk pilek sehat tidur', 'Berkaitan dengan keluhan yang anda sampaikan, penyakit yang dapat terjadi, yaitu :\r\n1. Asma bronkial, yaitu penyakit peradangan pada saluran pernapasan yang disebabkan reaksi alergi. Penyakit ini ditandai dengan sesak napas dengan suara \"ngi\".\r\n2. Rinitis alergi, yaitu peradangan pada lapisan mukosa hidung akibat reaksi alergi. Penyakit ini ditandai dengan bersin-bersin yang terjadi setiap pagi hari.\r\nReaksi alergi yang terjadi pada tubuh anda, merupakan penyakit yang diturunkan secara genetik. Penanganan yang paling utama adalah dengan menghindari pencetusnya. Reaksi alergi yang terjadi pada pagi hari, disebabkan udara dingin dan debu. Sehingga, gunakanlah baju dingin saat anda mulai merasakan udara dingin. Hindari menggunakan AC atau kipas angin pada pagi hari dan saat cuaca dingin. Jaga kebersihan ruangan tidur anda, terutama dari debu. Debu sering dijumpai dan menyebar di udara pada kipas angin. Sehingga, jika menggunakan kipas angin perlu agar anda secara teratur membersihkannya. Anda juga dapat mengatur waktu tidur, dengan tidur lebih awal dan bangun di waktu lebih pagi agar kualitas tidur anda tetap terjaga. Hindarilah batuk atau infeksi saluran napas karena dapat memperberat kondisi.\r\nAnda perlu berkonsultasi dengan dokter paru berkaitan dengan keluhan sesak napas yang dialami. Dokter akan meresepkan obat asma, yaitu obat yang berfungsi melapangkan saluran napas dan mengurangi produksi lendir saluran napas, jika diperlukan. Obat dapat berupa tablet yang diminum atau disemprotkan ke mulut atau dengan diasap (nebulizer).  '),
(14, 'punggung asma', 'Tidak benar bahwa keluhan asma dapat berkurang dengan pemijatan di daerah punggung. Asma merupakan penyempitan di saluran napas bawah akibat inflamasi yang terjadi kronis dan bersifat rekuren dengan mekanisme alergi yang mendasarinya. Terdapat gejala gangguan pernapasan seperti mengi, sesak, rasa berat di dada dan batuk.\r\nBerdasarkan lokasi anatomis, paru-paru dan saluran napas terdapa\r\nt didalam rongga dada yang dilindungi oleh tulang rusuk dan otot lurik yang melapisinya. \r\nSehingga secara logika gerakan pemijatan di daerah punggung tidak dapat secara langsung melebarkan saluran napas bawah yang sedang bermasalah saat serangan akut asma. \r\nUntuk menurunkan risiko kekambuhan, sebaiknya mulai pola hidup sehat, menghindari setiap pencetus, menggunakan obat bronkodilator/steroid inhalasi sebelum melakukan latihan atau olahraga untuk mencegah exercise induced asthma.  '),
(15, 'asma tangan alergi bronsolvan theophyliin lambung salbutamol ceteme', 'Dari info yang Anda sampaikan, adanya kebutuhan konsumsi obat salbutamol dan ceteme (Chlorpheneramini maleas) dapat Anda konsumsi secara bersamaan untuk mengurangi keluhan sesak karena asma yang ANda rasakan, Kedua obat ini dapat saling bekerja membantu mengurangi peradangan karena resiko alergi yang juga memicu serangan asma. Sedangkan salbutamol bekerja untuk membantu membuka kontraksi saluran nafas Anda yang menyempit pada saat serangan asma terjadi.\r\n\r\nNamun, yang perlu Anda perhatikan, sebaiknya kedua obat ini diresepkan langsug oleh dokter keluarga Anda atau dokter paru Anda sehingga dokter dapat mengetahui dan mengevalusai kondisi Anda selama masa perawatan. Hindari menggunakan obat dengan menentukan dosis obat tanpa petunjuk dokter yang merawat Anda.\r\n\r\nSelain itu, perlu kiranya Anda mempertimbangkan untuk berkonsultasi langsung dengan dokter spesialis saraf,berkaitan dengan keluhan kejang yang Anda alami bila sesak asma terjadi. Adanya gangguan suplai oksigen pada otak kemungkinan dapat menjadi penyebab terjadi kejang pada saat serangan asma. Bila Anda tidak melakukan konsultasi dan pemeriksaan ke dokter saraf, maka penanganan kejang yang terjadi akan tertunda dan resiko adanya gangguan saraf dapat semakin membebani Anda.\r\n\r\nDokter saraf akan merencanakan pemeriksaan penunjang untuk mengetahui fungsi sistem saraf terhadap kejang yang terjadi selama sesak, seperti pemeriksaan darah, ataupun pemeriksaan EEG otak atau scan otak.\r\n\r\nPengobatan akan diberikan berdasarkan hasil pemeriksaan yang didapatkan.  '),
(16, 'asma parah salbutamol', 'Pada dasarnya, asma adalah suatu penyakit yang tidak bisa sembuh secara total, melakinkan hanya dapat dikontrol agar gejalanya tidak sering timbul dengan menggunakan obat dan menghindari pencetus kambuhnya asma tersebut.\r\n\r\nSementara di rumah, bila timbul gejala sesak dapat dikonsumsi obat salbutamol yang sudah diresepkan sesuai anjuran dokter dan juga dibantu dengan menghindari hal-hal yang dapat menimbulkan gejala (misalnya debu, asap, udara dingin, dan lain-lain tergantung individu). Tetapi, apabila gejala yang anda rasakan timbul semakin sering, semakin berat, dan kurang membaik dengan obat yang sudah diresepkan, sebaiknya anda kembali memeriksakan diri ke dokter untuk dilakukan penilaian ulang mengenai keadaan asma anda, apakah perlu diberikan pengobatan melalui uap, pemberian tambahan obat untuk mengontrol gejala di rumah, atau bahkan perlu perawatan di rumah sakit.  '),
(17, 'asma keturunan hidung mulut nafas bunyi', 'Asama merupakan penyakit paru kronis, yang disebabkan oleh penyempitan saluran pernafasan, sehingga menyebabkan keluhan sesak nafas dan terkadang disertai batuk. Keluhan pasien dengan asma sering disertai dengan susah bernafas, bunyi nafas, keringat dingin, batuk, demam sampai sumbatan nafas yang berat.\r\nBeberapa kondisi di bawah ini merupakan pemicu kekambuhan penyakit asma, adalah:\r\n1. infeksi pernafasan\r\n2. reaksi alergi\r\n3. polusi\r\n4. stres atau kecemsan\r\n5. cuaca\r\n6. obat-obatan\r\n7. aktivitas fisik tertentu atau akvitas fisik yang berlebihan\r\nUntuk mengetahui kondisi klinis pasien selama serangan asma, maka sebaiknya dilakukan konsultasi langsung ke dokter spesialis paru atau ke UGD bila kondisi pasien gelisah dan sesak yang mengganggu. DOkter akan melakukan evaluasi dan pemeriksaan fisik serta pemeriksaan penunjang seperti pemeriksaan darah atau pemeriksaan radiologi. Hasil pemeriksaan akan menjadi dasarpenanganan pasien, baik dengan pemberian obat anti asma, ataupun bila diperlukan perawatan di rumah sakit tergantung dari kondisi pasien saat ini.\r\nBerkaitan dengan pertanyaan Anda, bila nafas Anda berat atau susah saat menutup mulut, maka hal ini menunjukkan adanya penyempitan saluran nafas di rongga hidung. Bila asam Anda mengalami kekambuhan dan hidung Anda tersumbat, maka hal ini akan memperberat keluhan Anda dan mengganggu kenyamanan Anda saat bernafas. Sehingga, evaluasi kemungkinan pemicu keluhan ini, apakah karena kelelahan fisik,kurang tidur , atau beberapa poin lain seperti penjelasan diatas. Dengan mencegah faktor resikonya,maka diharapkan keluhan ini tidak mudah berulang. \r\nDan bila Anda mengalami keluhan asma diawali dengan hidung tersumbat atau radang tenggorokan,maka sebaiknya segera ditangani atau diobati hidung tersumbat dan radang tenggorokan ini, sehingga tidak memperberat keluhan Anda. \r\nNamun, bila keluhan yang Anda rasakan sangat mengganggu, sebaiknya Anda melakukan konsultasi dan pemeriksaan langsung ke dokter spesialis paru Anda seperti uraian diatas. Dengan demikian, keluhan Anda segera pulih dan Anda semakin nyaman untuk beraktivitas.\r\nOleh karena itu, saya tidak dapat memberikan pengobatan tanpa melakukan pemeriksaan fisik langsung. \r\nUntuk saat ini, bila Anda merasakan kelelahan fisik,maka istirahatlah untuk pemulihan stamina Anda. Hindari makanan yang beresiko mengganggu kesehatan Anda seperti makanan yang memicu alergi bila Anda mempunyai riwayat tersebut, hindari gorengan, makanan instan, dan hindari tidur larut malam.   '),
(18, 'inhaler asma', 'Diagnosis asma (asma bronkhiale) sesungguhnya tidak boleh dibuat sembarangan tanpa pemeriksaan dokter sebelumnya. Masyarakat awam sering mengidentikkan asma dengan sesak napas, padahal sesungguhnya hal ini tidak selalu tepat. Secara klinis, penderita asma memang sering mengalami sesak napas, disertai batuk dan suara napas tambahan (mengi). Namun, keluhan ini terkadang bisa juga muncul akibat sebab lain, selain asma, misalnya bronkhitis, bronkhiolitis, serangan panik, GERD (gastroesophageal reflux disease), pneumonia, ISPA (infeksi saluran pernapasan akut), gastritis, dan sebagainya. Karenanya, pertanyaannya saat ini, sudahkah Anda memeriksakan keluhan Anda ke dokter dan didiagnosis asma? Bila sudah, lantas tidakkah dokter memberikan Anda penanganan untuk mengatasi keluhan Anda?\r\n\r\nPenanganan asma bisa dilakukan dengan beberapa pendekatan. Pada saat serangan datang, penderita asma bisa menggunakan obat pereda serangan asma, salah satunya dalam bentuk inhaler (obat semprot). Adapun komposisi inhaler asma ini memang bisa bermacam-macam, contohnya berupa bronkodilator, relaksan otot polos, anti radang, dan sebagainya. Pemilihan jenis inhaler ini tentu bisa bisa dilakukan sembarangan, melainkan harus dengan resep dan pengawasan dokter. Dosis dan cara penggunaan inhaler ini pun bisa bervariasi tergantung usia, postur tubuh, keparahan asma Anda, dan beragam faktor lainnya. Selain inhaler, ada beragam jenis sediaan obat lain untuk meredakan serangan asma, contohnya obat minum atau suntik. Tidak hanya itu, setelah serangan asma tertangani, Anda pun perlu mengkonsumsi obat untuk mengontrol asma, agar kekambuhan serangan asma bisa diminimalisasi.\r\n\r\nSebab itu, berkonsultasilah langsung dengan dokter atau dokter spesialis penyakit dalam agar diberikan penanganan yang terbaik sesuai dengan kondisi Anda ya.. Selain menggunakan obat dokter, agar serangan asma tidak selalu kambuh dan berulang, Anda sebaiknya kenali apa saja pencetus serangan asma Anda, dan hindari pencetus tersebut. Tidak lupa, jalani selalu pola hidup yang sehat, termasuk dengan teratur berolahraga, istirahat yang cukup, kelola stres dengan baik, dan jangan merokok.  '),
(19, 'asma keturunan pilek batuk berdahak ventolin inhaler salbutamol panas sakit kurus', 'Solusi terbaik untuk kekambuhan asma suami anda adalah dengan berkonsultasi dengan dokter, bila dirasa perlu anda bisa langsung berkonsultasi kepada dokter spesialis paru.  Dokter perlu melakukan penilaian secara langsung terhadap beberapa hal seperti frekuensi kekambuhan, bentuk serangan asma yang terjadi, frekuensi serangan pada malam hari dan beberapa hal lain karena pengobatan asma yang tepat bergantung juga pada hal-hal tersebut. Dan perlu diingat bahwa penyakit asma tidak dapat sembuh secara total, hanya dapat dikontrol agar tidak terjadi kekambuhan.\r\n\r\nDokter akan memutuskan lebih lanjut apakah penggunaan ventolin inhaler atau obat salbutamol, yang dalam hal ini sama-sama berisi salbutamol hanya dalam bentuk yang berbeda, perlu diteruskan atau tidak, dan apakah perlu tambahan obat lain untuk mengontrol gejala asma suami anda.\r\n\r\nUntuk penanganan sementara jika suami anda mengalami serangan asma, disarankan untuk menggunakan obat salbutamol berbentuk inhaler 4 semprot setiap 4 menit hingga maksimal 2x pemberian, bila tidak mengalami perbaikan segera bawa suami anda ke IGD rumah sakit terdekat untuk mendapat penanganan lebih lanjut.    '),
(20, 'perokok tidur asma batuk', 'Serangan asma bronkhiale (asma) memang bisa kambuh akibat beragam pencetus, tidak terkecuali asap (termasuk asap rokok), suhu dingin (biasanya suhu di pagi hari), hingga substansi udara yang banyak terdapat di pagi hari (misalnya serbuk sari, spora jamur, atau tungau debu). Tidak hanya itu, serangan asma juga bisa muncul karena pencetus lainnya, contohnya polusi udara, emosi dan stres psikis, refluks asam lambung, atau juga efek samping konsumsi obat tertentu (misalnya beta bloker, aspirin, atau ibuprofen). \r\n\r\nSaat timbul serangan, penderita biasanya akan mengalami sesak napas, batuk, disertai bunyi napas tambahan yang cukup mengganggu (mengi, ngik-ngik). Kondisi ini bisa terus berulang apabila pencetusnya tidak dihindari, termasuk juga bila Anda tidak menghentikan kebiasaan merokok Anda.\r\n\r\nSelain karena asma, bisa juga sesak napas dan batuk sebagaimana yang Anda alami muncul karena sebab lain, misalnya bronkhitis, bronkhiolitis, pneumonia, tuberkulosis, pneumothorax, efusi pleura, alergi, GERD (gastroesophageal reflux disease), gagal jantung kongestif, dan sebagainya. Kebanyakan dari kondisi ini juga besar risikonya terjadi pada orang yang memiliki kebiasaan merokok.\r\n\r\nPertanyaannya saat ini, sudahkah Anda memeriksakan keluhan Anda ke dokter? Apakah memang dokter pernah mendiagnosis Anda mengalami asma?\r\n\r\nSebaiknya, Anda periksakan diri Anda langsung ke dokter atau dokter spesialis penyakit dalam supaya dievaluasi, apakah benar kondisi Anda muncul karena asma, atau ada pencetus lainnya. Penanganan atas asma bisa dilakukan secara bervariasi, tergantung keparahannya dan juga kondisi Anda secara umum. Biasanya, saat serangan kambuh, dokter akan memberikan dulu terapi oksigen sekaligus memberikan beberapa obat untuk meredakan serangan asma. Setelah serangan teratasi, dokter bisa membekali Anda dengan beberapa pengobatan yang bisa Anda konsumsi untuk mengontrol agar serangan tidak terjadi berulang.\r\n\r\nSaran kami:\r\n•	Segera hentikan kebiasaan merokok\r\n•	Jauhi juga asap rokok, polusi, dan potensi pencetus asma lainnya (seperti disebutkan di atas)\r\n•	Makanlah dengan teratur, jangan terlambat\r\n•	Saat masih mengalami batuk, jangan berlebihan mengkonsumsi makanan dan minuman dingin, makanan berminyak, serta yang mengandung pemanis buatan\r\n•	Perbanyak beristirahat\r\n•	Kendalikan emosi Anda dengan baik\r\n•	Rajin berolahraga\r\n•	Tidak sembarangan mengkonsumsi obat tanpa saran dari dokter ');

--
-- Indexes for dumped tables
--

--
-- Indeks untuk tabel `data`
--
ALTER TABLE `data`
  ADD PRIMARY KEY (`id_data`);

--
-- AUTO_INCREMENT untuk tabel yang dibuang
--

--
-- AUTO_INCREMENT untuk tabel `data`
--
ALTER TABLE `data`
  MODIFY `id_data` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=21;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
